on:
  push:
    branches:
      - main


name: "build and release"
jobs:
    build:
      name: Build & Release
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '17.x'
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter build apk
        - uses: ncipollo/release-action@v1.12.0
          with:
            artifacts: "build/app/outputs/flutter-apk/app-release.apk"
            tag: "Releases"
            token: ${{ secrets.TOKEN }}













#push to main
