on:
  push:
    branches:
      - main


name: "build and release"
jobs:
    build:
      name: Build & Release
      runs-on: windows-latest
      steps:
        - uses: dart-lang/setup-dart@v1
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v1
          with:
            java-version: '12.x'
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '2.2.3'
            channel: 'stable'
        - run: flutter pub get
        - run: flutter build apk
        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/flutter-apk/*"
            tag: v1.0.${( github.run_number )}
            token: ${( secrets.TOKEN )}













#push to main
